[general]
framerate = 60
bars = 32
autosens = 1
sensitivity = 100

[input]
method = pulse
source = auto

[output]
method = ncurses
channels = stereo
mono_option = average
reverse = 0

[color]
background = '#070405'
foreground = '#ff3347'
gradient = 1
gradient_count = 5
gradient_color_1 = '#64101d'
gradient_color_2 = '#b11226'
gradient_color_3 = '#d62238'
gradient_color_4 = '#ff3347'
gradient_color_5 = '#d78388'

[smoothing]
noise_reduction = 77
monstercat = 1
waves = 0
